### ISSUE TITLE
Compatibility with laravel/nova >=v2.3.1

### ISSUE THREAD

**Issue by igorbabko** [ohdearapp/nova-ohdear-tool#9]
When I try to install latest version of `ohdearapp/nova-ohdear-tool` (v1.1.1 at this moment), it doesn't seem to be compatible with latest `laravel/nova` release (v2.3.1).

Am I missing something?

Thank you upfront!

```
    - ohdearapp/nova-ohdear-tool 1.1.1 requires laravel/nova ^2.0 -> no matching package found.
    - ohdearapp/nova-ohdear-tool 1.1.0 requires laravel/nova ^2.0 -> no matching package found.
    - Installation request for ohdearapp/nova-ohdear-tool ^1.1 -> satisfiable by ohdearapp/nova-ohdear-tool[1.1.0, 1.1.1].
```

**Comment by freekmurze** [comment]
I tagged a new release. Could you try again?

**Comment by igorbabko** [comment]
@freekmurze Great, it works!!
